
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jskrunner
 */
public class Calculator extends javax.swing.JFrame {

    public static String firstNumber;
    public static int firstNumberInt;
    public static String secondNumber;
    public static int secondNumberInt;
    public static int operator;
    public static boolean operatorPressed;
    public static boolean operatorUsed;
    public static int result;
    public static int maxDigits = 9;
    public static int length;
   

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        getContentPane().setBackground(Color.orange);
        
    }
    
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();
        eight = new javax.swing.JButton();
        five = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        six = new javax.swing.JButton();
        four = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        add = new javax.swing.JButton();
        subtract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField.setEditable(false);
        textField.setFont(new java.awt.Font("Silom", 1, 30)); // NOI18N
        textField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        eight.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        divide.setText(" ÷ ");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        multiply.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        multiply.setText("x");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        one.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        AC.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        AC.setText("A/C");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        zero.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        equal.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        add.setText("+");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        subtract.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        subtract.setText("-");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textField)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
       if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "7";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "7";
              textField.setText(secondNumber);
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
      
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "8";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "8";
              textField.setText(secondNumber);
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "9";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "9";
              textField.setText(secondNumber); 
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_nineActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
       if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "4";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "4";
              textField.setText(secondNumber); 
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
       if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "5";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "5";
              textField.setText(secondNumber);
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "6";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "6";
              textField.setText(secondNumber); 
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_sixActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "1";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "1";
              textField.setText(secondNumber);
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
       if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "2";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "2";
              textField.setText(secondNumber); 
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
       if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "3";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "3";
              textField.setText(secondNumber); 
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_threeActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        if(operatorPressed==false){
           if(length < maxDigits){
               firstNumber = firstNumber + "0";
               textField.setText(firstNumber);
               length = textField.getText().length();  
           }  
       }
       else{
           if(length < maxDigits){
              secondNumber = secondNumber + "0";
              textField.setText(secondNumber);
              length = textField.getText().length(); 
           }
           
       }
       if(firstNumber!=""){
           firstNumberInt = Integer.parseInt(firstNumber);
       }
       if(secondNumber!=""){
           secondNumberInt = Integer.parseInt(secondNumber);
       }
    }//GEN-LAST:event_zeroActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        if(operatorUsed==false){
            textField.setText( "÷");
            operatorPressed = true;
            operatorUsed = true;
            operator = 1;
            length = 0;
        }
    }//GEN-LAST:event_divideActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        if(operatorUsed==false){
            textField.setText( "x");
            operatorPressed = true;
            operatorUsed = true;
            operator = 2;
            length = 0;
        }
        
    }//GEN-LAST:event_multiplyActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        // TODO add your handling code here:
        if(operatorUsed==false){
            textField.setText( "-");
            operatorPressed = true;
            operatorUsed = true;
            operator = 3; 
            length = 0;
        }
        
    }//GEN-LAST:event_subtractActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(operatorUsed==false){
            textField.setText( "+");
            operatorPressed = true;
            operatorUsed = true;
            operator = 4;
            length = 0;
        }
        
    }//GEN-LAST:event_addActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        if(operator==1){
           result = firstNumberInt/secondNumberInt; 
           
        }
        else if(operator==2){
           result = firstNumberInt*secondNumberInt; 
        }
        else if(operator==3){
           result = firstNumberInt-secondNumberInt;   
        }
        else if(operator==4){
           result = firstNumberInt+secondNumberInt;  
        }
        textField.setText((Integer.toString(result)));
        firstNumber = "";
        secondNumber = "";
        result = 0;
        operatorUsed = false;
        operatorPressed = false;
        length = 0;
    }//GEN-LAST:event_equalActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        firstNumber = "";
        secondNumber = "";
        operatorPressed = false;
        operatorUsed = false;
        result = 0;
        textField.setText("");
        length = 0;
       
    }//GEN-LAST:event_ACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
                firstNumber = "";
                secondNumber = "";
                operatorPressed = false;
                operatorUsed = false;

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton add;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JTextField textField;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables

    
}
